version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/.
    container_name: frontend_rs
    tty: true
    ports:
      - "3000:3000"
    environment:
     - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app
    command: sh -c "npm run dev"
  backend:
    build:
      context: ./backend
      target: 'develop-stage'
    container_name: backend_rs
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: sh -c "cargo watch -x run"

volumes:
  cargo-cache:
  target-cache: